[gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1KdwFSxxih6bLNXnE61kxuP7t3UHvONUfU4X_ShSvx5w/edit?usp=sharing"
strength_url = "https://docs.google.com/spreadsheets/d/1KdwFSxxih6bLNXnE61kxuP7t3UHvONUfU4X_ShSvx5w/edit?gid=0#gid=0"
mind_url = "https://docs.google.com/spreadsheets/d/1KdwFSxxih6bLNXnE61kxuP7t3UHvONUfU4X_ShSvx5w/edit?gid=1131025189#gid=1131025189"